### PR TITLE
Rx memory

### PR DESCRIPTION
**Pull request by ybendito**

### CODE REVIEW

**Comment by ybendito** [comment]
**NetKVM-Win2025x64** - 7 failures, the same as with PR-1104
**NetKVM-Win11_22H2x64** - E2EPerf: well known, under investigation
Receiver failed to coalesce the minimum percentage of received packets (70%). Only 0% of receives were coalesced

**Comment by ybendito** [comment]
@kostyanf14 I've just aborted stuck HCK on virtlab1009.lab.eng.rdu2.redhat.com, hope it will run again

**Comment by ybendito** [comment]
@kostyanf14 Is it possible to wipe old tests from several months ago and leave only new ones?

**Comment by kostyanf14** [comment]
@ybendito No. GitHub does not allow to remove statuses only create/update.

**Review by YanVugenfirer — APPROVED** [review]

**Pull request merged**
