### PR TITLE
Win 8/8.1 solution cleanup

### PR DESCRIPTION
**Pull request by kostyanf14**

### CODE REVIEW

**Comment by YanVugenfirer** [comment]
fwcfg buildall.bat has Windows 8.1 (6.3) paramter in the call to inf2cat.
Can be removed later.

**Comment by YanVugenfirer** [comment]
Another point for removal of unneeded stuff: netkvm-base.txt, netkvm-add-rsc.txt, netkvm-add-rss.txt - can be consulidated.
RSS and RSC will be now always supported.
netkvm-add-uso.txt - might not be supported on early Windows 10 versions

Device.c in ivsjmem has inconcistence line endings

**Comment by YanVugenfirer** [comment]
\viocrypt still has Win8 config, can be fixed in the next PR

**Comment by YanVugenfirer** [comment]
When opening main solution file: "C:\Users\yan\dev\kvm-guest-drivers-windows\NetKVM\CoInstaller\netkvmco-vs2015.vcxproj : warning  : Wildcards in project items are not supported in VC projects and can cause unexpected behavior, instability and performance degradation in the Visual Studio IDE. Please refer to https://aka.ms/cpp/projectwildcards for supported options.
"

**Comment by YanVugenfirer** [comment]
ARM64 config is failing for some of the drivers when building from the main solution:
>ParaNdis_Debug.cpp
5>ParaNdis_Oid.cpp
5>ParaNdis_Protocol.cpp
4>LINK : fatal error LNK1104: cannot open file 'atls.lib'
4>Done building project "ProtocolService.vcxproj" -- FAILED.

**Comment by YanVugenfirer** [comment]
> ARM64 config is failing for some of the drivers when building from the main solution:
> 
> > ParaNdis_Debug.cpp
> > 5>ParaNdis_Oid.cpp
> > 5>ParaNdis_Protocol.cpp
> > 4>LINK : fatal error LNK1104: cannot open file 'atls.lib'
> > 4>Done building project "ProtocolService.vcxproj" -- FAILED.

This is the main issue in my opinion, other stuff can be fixed later.

**Review by YanVugenfirer — APPROVED** [review]

**Comment by YanVugenfirer** [comment]
> > ARM64 config is failing for some of the drivers when building from the main solution:
> > > ParaNdis_Debug.cpp
> > > 5>ParaNdis_Oid.cpp
> > > 5>ParaNdis_Protocol.cpp
> > > 4>LINK : fatal error LNK1104: cannot open file 'atls.lib'
> > > 4>Done building project "ProtocolService.vcxproj" -- FAILED.
> 
> This is the main issue in my opinion, other stuff can be fixed later.

Fixed. Spectre mitigation was not installed for VS2019

**Comment by YanVugenfirer** [comment]
@vrozenfe - up to you when to merge.

**Review by vrozenfe — APPROVED** [review]
Fine with me. 
We can merge it right now, and I will merge it downstream a bit later.
Bast,
Vadim.

**Pull request merged**
