### PR TITLE
[NO-SDV] test pr for viomem 

### PR DESCRIPTION
**Pull request by kostyanf14**

### CODE REVIEW

**Comment by ybendito** [comment]
@kostyanf14 Let's compare our systems
Attached: cd c:\windows\winsxs ; dir cbscore.dll tiworker.exe
[dir-cbscore.txt](https://github.com/user-attachments/files/17797545/dir-cbscore.txt)

**Comment by kostyanf14** [comment]
@YanVugenfirer @ybendito 

Ballon fail Win11 24H2 https://people.redhat.com/~kkostiuk/auto_hck/virtio-win/kvm-guest-drivers-windows/Balloon-Win11_24H2x64_host_uefi_viommu/2024_11_18_03_13_55/results.html

**Comment by YanVugenfirer** [comment]
@kostyanf14 Let's check that there is nothing with with Win11. If everything OK, let's open ticket.

**Comment by kostyanf14** [comment]
@YanVugenfirer We compared Win11 on CI and Win11 in Yuri setup. These are different versions of Win11.

**Comment by kostyanf14** [comment]
@YanVugenfirer 
Yes, different build number. Yuri has a newer.

**Comment by YanVugenfirer** [comment]
@kostyanf14 looks like a time for new Win11 VMs...

**Comment by ybendito** [comment]
On my setup the test on balloon also passed

**Comment by kostyanf14** [comment]
@ybendito @YanVugenfirer Reinstalling HCK-CI Win11 from en-us_windows_11_business_editions_version_24h2_x64_dvd_59a1851e.iso

**Pull request closed without merging**
