### PR TITLE
netkvm: do not complete packets in sending path

### PR DESCRIPTION
**Pull request by ybendito**
https://bugzilla.redhat.com/show_bug.cgi?id=1972487
Complete packets (i.e. get buffers from TX queue and
process waiting list) only when called from DPC (on
TX completion DPC or RX DPC). According to the tests
thos solves assertion "pCurrentNetBufferList" in the
NDPROT630 driver.

Signed-off-by: Yuri Benditovich <yuri.benditovich@daynix.com>

### CODE REVIEW

**Comment by ybendito** [comment]
This PR is not for immediate merge but first of all for intensive tests.
I hope it should prevent BSOD in RSSmini6 test under 2019 and 2022.
So I'd like it to run on 2019 and on 2022.
**If it looks OK on both**, I'd ask to run it additionally with 10 cycles of RSSmini6 test on 2022.

**Comment by ybendito** [comment]
1 failed test on 2019 does not seem related to the network driver: this is stuck power transition of USB HID.
@kostyanf14 As far as I remember the usb tablet is not recommended for HCK tests

**Comment by kostyanf14** [comment]
HLK 2022 results - https://www.dropbox.com/sh/m6zzblooqoqy2qf/AAAzGpgbv4WuFas8L3RdtqLua?dl=0&lst

**Comment by ybendito** [comment]
STACK_TEXT:  
ffffed04`853562e8 fffff802`5f5d0a34     : ffff8088`7b5c0ea0 ffff8088`7fcef718 ffff8088`78c0ebb0 fffff80d`8cf84261 : nt!DebugPrompt+0x17
ffffed04`853562f0 fffff80d`8cfe3963     : ffff8088`78c139f0 00000000`00000000 fffff80d`8d0c3fd0 81010101`01010100 : nt!DbgPrompt+0x44
ffffed04`85356340 fffff80d`8cf8760d     : fffff80d`00000001 fffff80d`8d0ad520 00000000`000002e8 ffffed04`85356200 : ndprot683!CNDTKeLog::NDTKeBreakPoint+0x323
ffffed04`853563a0 fffff80d`8cf7feef     : ffff8088`78c14800 ffffed04`85356598 ffffed04`85356608 ffff8088`7fcef360 : ndprot683!CNDTSolicitedBindingManager::NDTInitiateBindToAdapter+0xcdd
ffffed04`85356550 fffff80d`8cf7bbf0     : ffff8088`78c14800 ffff8088`7fcef340 ffffb781`b3ae2298 00000000`000003d8 : ndprot683!CNDTBindingManager::OpenAdapterCmdHandler+0x49f
ffffed04`85356640 fffff80d`8cf74831     : ffff8088`78c0ae90 00000000`3c000001 ffff8088`7fcef340 00000000`000003d8 : ndprot683!CNDTProtocolDriver::OnNdisTestCommand+0x240
ffffed04`85356700 fffff80d`8cfe549b     : 00000000`3c000001 ffff8088`7fcef340 ffff8088`000003d8 ffffb781`b3ae2298 : ndprot683!CNDTProtocolManager::OnNdisTestCommandForProtocol+0x301
ffffed04`853567b0 fffff80d`8cf77747     : ffff8088`78c02520 ffff8088`7b2debc0 ffff8088`7b5c0ea0 ffff8088`7b5c0f70 : ndprot683!CNDTCommandProcessor::ProcessCommand+0x3bb
ffffed04`85356870 fffff802`5f3a8207     : ffff8088`7b2debc0 ffff8088`7b5c0ea0 ffff8088`00000001 ffff8088`00000000 : ndprot683!NDTIoCtlDispatchHandler+0x147
ffffed04`853568b0 fffff802`5fa5a458     : ffff8088`7b5c0ea0 ffff8088`7b2debc0 00000000`00000000 fffff802`5f4ce88b : nt!IopfCallDriver+0x53
ffffed04`853568f0 fffff802`5f4432cb     : ffff8088`7b5c0ea0 00000000`00000002 00000000`00000001 ffff8088`7fdc5380 : nt!IovCallDriver+0x264
ffffed04`85356930 fffff802`5f789cd9     : ffff8088`7b5c0ea0 00000000`00000000 ffffed04`85356ca0 ffff8088`7fb2f2e8 : nt!IofCallDriver+0xe77bb
ffffed04`85356970 fffff802`5f799898     : ffff8088`7b5c0ea0 ffffed04`85356ca0 00000000`00122006 ffffed04`85356ca0 : nt!IopSynchronousServiceTail+0x189
ffffed04`85356a10 fffff802`5f799f46     : 00000000`00000000 00000000`000006bc 00000000`00000000 00000234`85a3b4b8 : nt!IopXxxControlFile+0x5d8

**Comment by ybendito** [comment]
https://www.dropbox.com/sh/m6zzblooqoqy2qf/AAAzGpgbv4WuFas8L3RdtqLua?dl=0&lst=

**Comment by ybendito** [comment]
Hardware-enforced Stack Protection Compatibility Test:  
Cause : INFORMATION: Task "Run Test" Failed Because the Task With TaskTimeout Flag Was running after the Timeout period 1800000 MilliSeconds

**Comment by YanVugenfirer** [comment]
> 2022: Hardware-enforced Stack Protection Compatibility Test:
> Cause : INFORMATION: Task "Run Test" Failed Because the Task With TaskTimeout Flag Was running after the Timeout period 1800000 MilliSeconds

@kostyanf14 isn't manual test? Why it is running?

**Comment by kostyanf14** [comment]
@YanVugenfirer Yes 'Hardware-enforced Stack Protection Compatibility Test' is a manual test, but it exists in the playlist.

**Comment by YanVugenfirer** [comment]
> @YanVugenfirer Yes 'Hardware-enforced Stack Protection Compatibility Test' is a manual test, but it exists in the playlist.

I think we should add configuration of filtering out the manual tests

**Comment by kostyanf14** [comment]
HCK-CI/NetKVMcustom-Win2022x64 - https://www.dropbox.com/sh/ugax8risx7p6kvf/AACfqaA6IsH6F8Bnlu7Fg_5Da?dl=0&lst=

**Review by YanVugenfirer — APPROVED** [review]

**Review by ybendito — COMMENTED** [review]
I see why this does not do what it pretends to do:
Let's assume sich a flow:
* we leave SendMapped(false, ...)
* we leave the protected scope
* we're about to process pending packets in waiting list
* at this moment DPC comes, does the NB completions and enters it's PostProcessPendingTask
* Some of NBLs in Waiting list might become completed
* Send path will report them

**Pull request merged**
