### PR TITLE
Whql fixes #2

### LINKED ISSUE #2: driver bluescreens in R2 VM
We are running an Ubuntu-based Linux cluster using qemu/KVM to create a virtualized environment.  Guest OS is Win2k8 R2 SP1 x64.  Our system has dual redundant storage controllers and the Linux hypervisors are configured for multipathed IO.  When we run failover testing on the storage controllers the HV appears to be fine but we are getting occasional bluescreens from the VirtIO storage driver in the guest.

DRIVER_IRQL_NOT_LESS_OR_EQUAL
STOP: 0xD1 (0x168, 0x2, 0x0, 0xXFFFFF88000FDA1D2)
viostor.sys

Driver version is 61.63.103.2200 pulled from http://alt.fedoraproject.org/pub/alt/virtio-win/latest/images/bin/.

Is there any driver update which might address this issue, or is anyone interested in trying to debug the problem?  We can reproduce the issue as needed and provide memory dumps and other debug information.

Thanks!

### PR DESCRIPTION
**Pull request by hammerg**

### CODE REVIEW

**Comment by janisozaur** [comment]
how does that concern WHQL? Is this to have the drivers certified? Is there an issue to track progress? Or is there some analysis that checks for compliance?

**Comment by YanVugenfirer** [comment]
We are running HCK tests as CI. This PR fixed the issues with the previous commits. 

virtio-fs is a functional work in progress. You are more than welcomed to test it.

**Comment by janisozaur** [comment]
Where can I see the CI status?

**Comment by YanVugenfirer** [comment]
Click on the green "V" mark near the last commit of the pull request. The interface on the closed PR little bit awkward.

**Comment by YanVugenfirer** [comment]
When you click on the "Details" you are redirected to the DropBox folder that holds all the logs.

**Comment by janisozaur** [comment]
Oh, somehow I haven't noticed the tick. Have you considered doing GitHub actions for CI?

**Comment by YanVugenfirer** [comment]
I don't think it is possible to run HCK tests on top of GitHub actions. Definitely for the network driver (we are orchestrating underlying network infrastructure in a specific way).
Even for the "regular" HCK run we need at least two VMs to work simultaneously. One to run the HCK studio and another test client with device under test. Moreover, the VM with the device under test, should have the device.

**Pull request merged**
