### PR TITLE
[netkvm] add surprise remove attribute

### PR DESCRIPTION
**Pull request by zjmletang**
Signed-off-by:  Zhang JianMing <zhangjianming.zjm@alibaba-inc.com>

for the problem description
please visit virtio-win#1002

### CODE REVIEW

**Comment by YanVugenfirer** [comment]
Waiting for CI.
@zjmletang, did you run HCLK on Windows 10 (client version)?

**Comment by zjmletang** [comment]
> Waiting for CI. @zjmletang, did you run HCLK on Windows 10 (client version)?
No, I haven't, as I currently do not have a local HLK test environment. I was under the impression that HLK tests would be conducted automatically after submitting a PR, so I didn't perform any. Do I need to test this myself?

**Comment by YanVugenfirer** [comment]
@zjmletang Our CI runs HCK tests for Windows Server additions, but we don't have the capacity yet to run for Windows client versions.
Let's wait for the current CI to run and then decide.

**Comment by zjmletang** [comment]
@YanVugenfirer , I've observed that one of the test items has failed. Is there any action required from my side? Curiously though, I saw that the identical test item succeeded on HCK-CI/NetKVM-Win2019x64 (Fedora Linux 37, QEMU v8.1.0-1171-gda1034094d). Could you please explain the reason for this discrepancy?

**Comment by YanVugenfirer** [comment]
@zjmletang "NICStrictPropertyValidation" failed because it was not updated in the CI image. Unfortunately the scripts that runs as part of this test is not a distributed with HCK, but it should be downloaded from MS repository.

"GlitchFreeDevice" - we know that this test is problematic and might fail. Some packets are getting lost. The test instructs the driver to limit the number of packets that are reported to OS in each DPC.

Anyway, no actions from your side needed. Let me see if those tests are enough, or still I want to see also Desktop version of Windows to run.

**Comment by zjmletang** [comment]
> @zjmletang "NICStrictPropertyValidation" failed because it was not updated in the CI image. Unfortunately the scripts that runs as part of this test is not a distributed with HCK, but it should be downloaded from MS repository.
> 
> "GlitchFreeDevice" - we know that this test is problematic and might fail. Some packets are getting lost. The test instructs the driver to limit the number of packets that are reported to OS in each DPC.
> 
> Anyway, no actions from your side needed. Let me see if those tests are enough, or still I want to see also Desktop version of Windows to run.

ok. thanks

**Review by YanVugenfirer — APPROVED** [review]

**Comment by ybendito** [comment]
@zjmletang Can you please just rebase the PR to the latest master and force push. We want to run Win11 test on it and this require rebase.

**Comment by zjmletang** [comment]
> @zjmletang Can you please just rebase the PR to the latest master and force push. We want to run Win11 test on it and this require rebase.

done

**Comment by zjmletang** [comment]
@YanVugenfirer I've noticed that this test（DF - Reboot Restart with IO During (Reliability)） has failed, whereas this test was successful previously.   I'd like to inquire about the potential implications of this test's failure.

**Comment by ybendito** [comment]
> @YanVugenfirer I've noticed that this test（DF - Reboot Restart with IO During (Reliability)） has failed, whereas this test was successful previously. I'd like to inquire about the potential implications of this test's failure.

There is no WTL file, only testlog.txt (which does not reveal any problem)
From the HCKX:
Cause : Failed to Start the Task
Cause : Failed to Get the user Token
Failure : Failed to Start the Task "Run Test"
Cause : Failed to Get User Token ""\"" For Task "Run Test"
Cause : No Active LoggedOn Session Found.

@YanVugenfirer @kostyanf14 
Did you see such an effect in the past?

**Comment by YanVugenfirer** [comment]
Looks like that for some reason the test failed to run. But also can indicate mid test crash.

**Review by ybendito — APPROVED** [review]

**Pull request merged**
