### PR TITLE
vioscsi: move request handler from INTx ISR to DPC

### PR DESCRIPTION
**Pull request by irudakov77**
When MSIs are disabled, the OS uses INTx and calls VioScsiInterrupt to
handle interrupts. This ISR eventually calls CompleteRequest on DIRQL.
Sometimes StorPortFreeContiguousMemorySpecifyCache is called during
request completion, but it requires IRQL <= DPC_LEVEL, not DIRQL.
Sometimes it leads to deadlock. It is necessary to complete requests in
IsrDpc, like VioScsiMSInterrupt does.

Signed-off-by: Ilya Rudakov <irudakov@virtuozzo.com>

### CODE REVIEW

**Comment by vrozenfe** [comment]
@irudakov77 
Hi Ilya, 

Thank you for spotting this issue out. Do I understand correctly that the only condition to hit this issue is to disable MSI and change the number of physical breaks to be more than 64?

Cheers,
Vadim.

**Comment by irudakov77** [comment]
Hi Vadim,

Yes. We have a clear reproduction. When migrating guests from another product, we have a deadlock with a probability of 10-15%.

```
Child-SP RetAddr Call Site
00 ffffd001`275e4648 fffff801`7b3e4f14 nt!DbgBreakPointWithStatus
01 ffffd001`275e4650 fffff801`7b2c5311 nt! ?? ::FNODOBFM::`string'+0x8024
02 ffffd001`275e46e0 fffff801`7b220ac5 nt!KeClockInterruptNotify+0x91
03 ffffd001`275e4900 fffff801`7b33a713 hal!HalpTimerClockIpiRoutine+0x15
04 ffffd001`275e4930 fffff801`7b3c96aa nt!KiCallInterruptServiceRoutine+0xa3
05 ffffd001`275e4970 fffff801`7b3c9b57 nt!KiInterruptSubDispatchNoLockNoEtw+0xea
06 ffffd001`275e49c0 fffff801`7b30754f nt!KiInterruptDispatchNoLockNoEtw+0x37
07 ffffd001`275e4b50 fffff801`7b314405 nt!KxWaitForLockOwnerShip+0x27
08 ffffd001`275e4b80 fffff801`7b514311 nt!ExFreeLargePool+0x4b5
09 ffffd001`275e4c20 fffff801`7b313832 nt!ExFreePoolWithTag+0x301
0a ffffd001`275e4cc0 fffff800`a2821714 nt!MmFreeContiguousMemory+0x232
0b ffffd001`275e4d10 fffff800`a40cb7f4 storport!StorPortExtendedFunction+0x3e7
0c (Inline Function) -------`------- vioscsi!StorPortFreeContiguousMemorySpecifyCache+0x1a [c:\program files (x86)\windows kits\10\include\10.0.17763.0\km\storport.h @ 11452]
0d (Inline Function) -------`------- vioscsi!PostProcessRequest+0x2ef [c:\jenkins\workspace\virtio\virtio-win\kvm-guest-drivers-windows\vioscsi\vioscsi.c @ 1640]
0e (Inline Function) -------`------- vioscsi!CompleteRequest+0x32d [c:\jenkins\workspace\virtio\virtio-win\kvm-guest-drivers-windows\vioscsi\vioscsi.c @ 1656]
0f ffffd001`275e4e60 fffff800`a40cdc6d vioscsi!HandleResponse+0x6e0 [c:\jenkins\workspace\virtio\virtio-win\kvm-guest-drivers-windows\vioscsi\vioscsi.c @ 1026]
10 ffffd001`275e4ec0 fffff800`a283e835 vioscsi!VioScsiInterrupt+0x23d [c:\jenkins\workspace\virtio\virtio-win\kvm-guest-drivers-windows\vioscsi\vioscsi.c @ 1103]
11 ffffd001`275e4f10 fffff801`7b33a713 storport!RaidpAdapterInterruptRoutine+0x81
12 ffffd001`275e4f70 fffff801`7b3c9468 nt!KiCallInterruptServiceRoutine+0xa3
13 ffffd001`275e4fb0 fffff801`7b3c96f7 nt!KiInterruptSubDispatch+0x108
14 ffffd001`239736a0 fffff801`7b515c07 nt!KiInterruptDispatch+0x37
15 ffffd001`23973830 fffff801`7b514884 nt!ExDeferredFreePool+0x1f7
16 ffffd001`239738b0 fffff800`a4287dc1 nt!ExFreePoolWithTag+0x874
17 ffffd001`23973950 fffff800`a4288391 Ntfs!NtfsCleanupIrpContext+0x481
18 ffffd001`239739f0 fffff800`a43488be Ntfs!NtfsExtendedCompleteRequestInternal+0xf1
19 ffffd001`23973a30 fffff800`a43347b5 Ntfs!NtfsCommonClose+0xa3b
1a ffffd001`23973b00 fffff801`7b2e3b7f Ntfs!NtfsFspCloseInternal+0x1bd
1b ffffd001`23973c90 fffff801`7b35bda2 nt!ExpWorkerThread+0x69f
1c ffffd001`23973d40 fffff801`7b3cfc36 nt!PspSystemThreadStartup+0x18a
1d ffffd001`23973da0 00000000`00000000 nt!KiStartSystemThread+0x16

```
MSI is disabled, the request being completed has more than 64 physical breaks. We will figure out why the MSI was disabled, but the driver should still not cause the deadlock in this case. :)

**Comment by vrozenfe** [comment]
Sure, 
BSOD is not an option in any case, and has to be fixed.
Just for the record:
- completion of SRB request is perfectly fine ( as long as it is bug-free :) ) and used to be some kind of performance optimization for IRQ driven systems. 
- I was thinking about  increasing number of physical segments up to 256 or 512, just like we already have in virtio-blk https://github.com/virtio-win/kvm-guest-drivers-windows/blob/master/viostor/virtio_stor.h#L90 and completely eliminate dynamic memory allocation in SRB processing path. It can improve  performance a bit for big blocks transfer.
- 
Apart from that, I'm perfectly fine with you patch and ready to approve and commit it if you want.

Best,
Vadim.

**Comment by irudakov77** [comment]
Hi Vadim,

1. Well, I knew a few cases where ISR + DPC interrupt handling was better for overall system performance than using ISR alone:) I ran simple perf test: with this patch, the perf is at least as good.
2. It seems to me that extra-large blocks are transferred quite rarely, I have not seen such during my patch testing and we have not get complaints about poor disk performance on large blocks. It is possible that the situation will change in the future and such optimization will become necessary, but now could you commit this patch please?

Thanks,
Ilya

**Comment by vrozenfe** [comment]
Hi Ilya,

No problem. Thanks a lot for your PR. Merging it right now.
But just for the record - SQL server, for example, can use
512KB blocks for Read-Ahead Scans, and 1MB blocks for
Backup/Restore, Checkpoints and Lazywrite operations.

Best,
Vadim.

**Comment by irudakov77** [comment]
Vadim,

Thanks for info about SQL server, I have already decided to make my own tests for large blocks, then I'll tell you what happened.

Regards,
Ilya

**Pull request merged**
