### PR TITLE
Viomem dmar compatibility (disable DMAR)

### PR DESCRIPTION
**Pull request by ybendito**

### CODE REVIEW

**Review by YanVugenfirer — APPROVED** [review]

**Comment by ybendito** [comment]
Win11-iommu: 1 test failed on HCK (twice according to @kostyanf14), passed 2 times on my fresh local HCK.

**Comment by ybendito** [comment]
@kostyanf14 Let's run only this test 10 times on your HCI-CI
DF - Reinstall with IO Before and After

**Comment by ybendito** [comment]
Exact failure is:
A crash with exception code 0xC0000005 occurred in module "cbscore.dll" in process "TiWorker.exe"
[Found by googling](https://techcommunity.microsoft.com/discussions/windowsinsiderprogram/regarding-triworker-exe-crash-to-cbscore-dll-with-an-error-code-of-c0000005-/4184210)

**Comment by ybendito** [comment]
@kostyanf14 Any update?

**Comment by kostyanf14** [comment]
@YanVugenfirer New Server 2025 and Win11 24H2 passed

**Comment by YanVugenfirer** [comment]
@kostyanf14 please notify QE about the latest versions

**Pull request merged**
