### PR TITLE
viofs-svc: Fix issue with allocating 0 bytes

### PR DESCRIPTION
**Pull request by TexKiller**
If FUSE_FALLOCATE is called passing a length of 0 it returns an error.
Since allocating 0 bytes is expected to just do nothing, it is better to prevent the call to FUSE_FALLOCATE and report a success instead.
This should fix the issue when creating new files from Windows Explorer.

Signed-off-by: Tex Killer Tex.Killer@hotmail.com

### CODE REVIEW

**Review by YanVugenfirer — CHANGES_REQUESTED** [review]
Hello,

Can you please add "Signed-off-by" with your name and email as part of the commit message.

For example:
Signed-off-by: Yan Vugenfirer <yvugenfi@redhat.com>

Thanks,
Yan.

**Comment by TexKiller** [comment]
> Hello,
> 
> Can you please add "Signed-off-by" with your name and email as part of the commit message.
> 
> For example:
> Signed-off-by: Yan Vugenfirer [yvugenfi@redhat.com](mailto:yvugenfi@redhat.com)
> 
> Thanks,
> Yan.

Done.

**Review by YanVugenfirer — APPROVED** [review]
OK from my point of view (although I prefer the usage of real name in Signed-off-by line for the licensing purposes ;) ).

Waiting for @hammerg review after he will be back from vacation.

Best regards,
Yan.

**Comment by hammerg** [comment]
Thanks for patch.

Can you please provide a scenario on how to reproduce the bug? I didn't see an error when a file is created using Windows Explorer.

    Gal.

**Comment by TexKiller** [comment]
> Thanks for patch.
> 
> Can you please provide a scenario on how to reproduce the bug? I didn't see an error when a file is created using Windows Explorer.
> 
> ```
> Gal.
> ```

Well, whenever I try to create a new text file on the VirtioFS drive on Windows 10 it fails without this patch, showing an error about permissions. After that, when I refresh the drive I see that some empty file was created named "New Text File.txt" and I can rename it, but it would be better to not get a permission error in the first place.

**Comment by YanVugenfirer** [comment]
Hello @TexKiller,

Can you please provide complete info regarding your scenario:
1. What's the setup on the host side (qemu version, qemu command line. virtio-fs config on host side)
2. Windows version, if it is Windows 10 or Windows Server 2016 and up, please provide release or build version as well.

Thanks a lot!

**Comment by hammerg** [comment]
> > Thanks for patch.
> > Can you please provide a scenario on how to reproduce the bug? I didn't see an error when a file is created using Windows Explorer.
> > ```
> > Gal.
> > ```
> 
> Well, whenever I try to create a new text file on the VirtioFS drive on Windows 10 it fails without this patch, showing an error about permissions. After that, when I refresh the drive I see that some empty file was created named "New Text File.txt" and I can rename it, but it would be better to not get a permission error in the first place.

Thanks for the patch and your reply. To be honest, I have no clue what went wrong and how this simple bug scenario was slipped through.

**Comment by YanVugenfirer** [comment]
@hammerg - please review "DF - Sleep and PNP (disable and enable) wit…er (Reliability)" failure.

**Comment by YanVugenfirer** [comment]
@hammerg - also please either squash your last commit, or add a proper commit message to it. Thanks.

**Comment by hammerg** [comment]
> @hammerg - please review "DF - Sleep and PNP (disable and enable) wit…er (Reliability)" failure.

@YanVugenfirer Please fix the CI first :-P

The HCK tests should not run when the virtiofs service is changed.

BTW: Do you know how to squash my change into one commit via the web interface or should I do it locally and resubmit the PR?

    Thanks, Gal.

**Comment by YanVugenfirer** [comment]
@Basils - 

> > @hammerg - please review "DF - Sleep and PNP (disable and enable) wit…er (Reliability)" failure.
> 
> @YanVugenfirer Please fix the CI first :-P
> 
> The HCK tests should not run when the virtiofs service is changed.
> 
@Basils - didn't you add the triggers already?

**Comment by YanVugenfirer** [comment]
> BTW: Do you know how to squash my change into one commit via the web interface or should I do it locally and resubmit the PR?
> 

I don't see how you can do it :(

But I wonder if this is possible https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request chaning branch to another user, and then you could rebase in your own branch.

> ```
> Thanks, Gal.
> ```

**Comment by TexKiller** [comment]
> > BTW: Do you know how to squash my change into one commit via the web interface or should I do it locally and resubmit the PR?
> 
> @hammerg
> I don't see how you can do it :(
> 
> But I wonder if this is possible https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request chaning branch to another user, and then you could rebase in your own branch.
> 
> > ```
> > Thanks, Gal.
> > ```

Do you guys want me to rewrite the commit history of the PR's branch to undo @hammerg 's commit? Then he could push a new correct one.

**Comment by YanVugenfirer** [comment]
@TexKiller if you can apply his commit to your branch and squash with yours (with "git rebase -i" for example). Then force push the branch, PR will be updated automatically.

And please add his sign-off: Gal Hammer <ghammer@redhat.com>

Thanks.

**Comment by TexKiller** [comment]
> @TexKiller if you can apply his commit to your branch and squash with yours (with "git rebase -i" for example). Then force push the branch, PR will be updated automatically.
> 
> And please add his sign-off: Gal Hammer [ghammer@redhat.com](mailto:ghammer@redhat.com)
> 
> Thanks.

Is this acceptable?

**Comment by hammerg** [comment]
Thanks again @TexKiller. I hope we'll pass the CI checks this time ;-).

**Review by hammerg — APPROVED** [review]

**Comment by YanVugenfirer** [comment]
@TexKiller Thanks a lot!

**Comment by YanVugenfirer** [comment]
@TexKiller @hammerg - thanks a lot. Merged.

**Pull request merged**
