### PR TITLE
[packaging] Fixup buildall.bat

### PR DESCRIPTION
**Pull request by benyamin-codez**
Made directory creation conditional (if not exist)
Removes reference to non-existent file COPYING

### CODE REVIEW

**Comment by kostyanf14** [comment]
@YanVugenfirer Do we still need this folder for anything?

**Review by YanVugenfirer — APPROVED** [review]

**Comment by kostyanf14** [comment]
@vrozenfe Do we still need this folder for anything?

**Comment by benyamin-codez** [comment]
@YanVugenfirer @vrozenfe @kostyanf14 

This basically creates the old unattended floppy disk style OEM TXTSETUP driver disk tree, in this case for `viostor`...

If you think it worthwhile, I'm happy to add a commit to delete it here...
...and one each for PRs #1211 and #1212 to remove it there also... 8^d
Let me know.

**Comment by vrozenfe** [comment]
> @vrozenfe Do we still need this folder for anything?

Starting with RHEL-8, we no longer provide VFD images.
The main reason, as far as I remember, is that RHEL's QEMU 
doesn't support floppy disk controllers anymore.
But who knows what might happen in the future?

Also, if we ever do a full cleanup, we could remove all OEM 
and VFD related stuff from the virtio-win and packaging 
repositories.

Cheers,
Vadim.

**Comment by YanVugenfirer** [comment]
> Also, if we ever do a full cleanup, we could remove all OEM
> and VFD related stuff from the virtio-win and packaging
> repositories.

OK, so let's remove all VFD related stuff @benyamin-codez

**Comment by benyamin-codez** [comment]
@YanVugenfirer @vrozenfe 
> > Also, if we ever do a full cleanup, we could remove all OEM
> > and VFD related stuff from the virtio-win and packaging
> > repositories.
> 
> OK, so let's remove all VFD related stuff

So do you wish me to redo this PR to delete the `[packaging]` folder and associated artefacts in clean and build...?

Will this break anything else in virtio-win, including the packaging repos...?
Are there any other OEM or VFD related stuff that need to be removed also...?
I'm not familiar enough with the rest of the tree or the packaging repos to even know where to start...

**Comment by kostyanf14** [comment]
@benyamin-codez 

>So do you wish me to redo this PR to delete the [packaging] folder and associated artefacts in clean and build...?

Yes

>Will this break anything else in virtio-win, including the packaging repos...?

It shouldn't break

**Comment by benyamin-codez** [comment]
Changes made to delete:

1. Folder - New PR [#1224](https://github.com/virtio-win/kvm-guest-drivers-windows/pull/1224)
2. Reference in `root\clean.bat` - Added to PR [#1211](https://github.com/virtio-win/kvm-guest-drivers-windows/pull/1211)
3. Reference in `root\buildAll.bat` - Added to PR [#1212](https://github.com/virtio-win/kvm-guest-drivers-windows/pull/1212)

**Pull request closed without merging**
