### PR TITLE
RHEL-65784: CI: Enable code style chacking with clang-format [CI-NO-BUILD]

### PR DESCRIPTION
**Pull request by kostyanf14**
Add empty config for clang-format.

Jira: https://issues.redhat.com/browse/RHEL-65784

### CODE REVIEW

**Comment by kostyanf14** [comment]
@YanVugenfirer 

Example results with fail https://github.com/virtio-win/kvm-guest-drivers-windows/actions/runs/11839602646/job/32991430107?pr=1192

**Comment by kostyanf14** [comment]
@YanVugenfirer 

Results when everything is ok https://github.com/virtio-win/kvm-guest-drivers-windows/actions/runs/11839831500/job/32992230697

**Review by YanVugenfirer — APPROVED** [review]

**Comment by kostyanf14** [comment]
rerun tests

**Comment by YanVugenfirer** [comment]
Merging 

@kostyanf14 please update Wiki and contributing.md

**Pull request merged**
