### PR TITLE
Add multi-touch tablet support.

### PR DESCRIPTION
**Pull request by ivellioscolin**
The patch set includes 7 patches which enabling the multi-touch (MT) support with VirtIO HID tablet implementation adjustment, together with some features:

1. vioinput: Change tablet report descriptor to hybrid mode
2. vioinput: Handle IOCTL_HID_GET_FEATURE for tablet to report max contacts
3. vioinput: Add EventToCollectFunc() before delivering the actual report
4. vioinput: Add identifiable multi-touch support for HID tablet
5. vioinput: Add anonymous multi-touch support for HID tablet
6. vioinput: Add scan time to tablet report descriptor
7. vioinput: Add touch contact width/height to HID tablet.

The patch set have been tested on both Windows 7 SP1 and Windows 10 with upstream QEMU tag v4.2.0 and latest master. A typical QEMU command line is to add below extra virtio-input-host device as below, where eventX is your touch input device:
```
-device virtio-input-host,id=touch0,evdev=/dev/input/eventX
```
i.e. The actual full QEMU command line during my testing is:
```
qemu-system-x86_64 \
	-nodefaults \
	-enable-kvm -m 4096 -smp 2 -M q35 -cpu host -k en-us -machine kernel_irqchip=on \
	-bios /usr/share/qemu/OVMF.fd \
	-device qxl-vga -display sdl -full-screen \
	-device ide-hd,drive=disk1,bus=ide.0,unit=0 \
	-drive file=/home/os/win10_1909_x64_gpt.qcow2,if=none,format=qcow2,id=disk1 \
	-device virtio-input-host,id=touch0,evdev=/dev/input/event6
```

V2:
Split the bit patch to 7.
Rebase to latest upstream master.
Revise PR description.

Signed-off-by: Colin Xu <colin.xu@gmail.com>

### CODE REVIEW

**Comment by YanVugenfirer** [comment]
@ivellioscolin Thank you very much for the pull request!

I have several comments:
1. The commit is very big, is it possible to split the commit?
2. Did you test the changes on Windows 7 (pre-Win8 systems in general)?
3. Are there any corresponding changes in QEMU that we should be aware of?
4. Can you post your test setup configuration (QEMU command line)?

Thank you.

**Comment by ivellioscolin** [comment]
> @ivellioscolin Thank you very much for the pull request!
> 
> I have several comments:
> 
> 1. The commit is very big, is it possible to split the commit?
> 2. Did you test the changes on Windows 7 (pre-Win8 systems in general)?
> 3. Are there any corresponding changes in QEMU that we should be aware of?
> 4. Can you post your test setup configuration (QEMU command line)?
> 
> Thank you.

Sure, let me

**Comment by ivellioscolin** [comment]
> @ivellioscolin Thank you very much for the pull request!
> 
> I have several comments:
> 
> 1. The commit is very big, is it possible to split the commit?
Now I split them to 7 smaller patch so that they can be applied one by one while not breaking current version and easy to bisect. Patch 4 is still kinda big but can't be split further. I tried to move most independent part to the first 3 patches.
> 2. Did you test the changes on Windows 7 (pre-Win8 systems in general)?
Yes, tests on a fresh cooked Windows 7 SP1 from ISO. It requires "Tablet PC Components" feature which should already been turned on after fresh installation.
> 3. Are there any corresponding changes in QEMU that we should be aware of?
No other change required in QEMU. All tests are running based on upstream tag v4.2.0.
> 4. Can you post your test setup configuration (QEMU command line)?
Updated in PR description.
> 
> Thank you.
Have other tasks so the PR refresh delays.
Comment on each questions in-line.

**Comment by YanVugenfirer** [comment]
Thanks for the update! I will review it.

**Pull request merged**
