### PR TITLE
netkvm: declare DMAR compatibility in the INF file

### PR DESCRIPTION
**Pull request by ybendito**
https://issues.redhat.com/browse/RHEL-1215

Enable DMAR if driver verifier is enabled

### CODE REVIEW

**Comment by ybendito** [comment]
Win2025 - something strange, most of the tests failed due to error with logs copy, trying in local env 
2019 - somehow there are no logs link in HTM results
Win11 - tests did not run

**Comment by YanVugenfirer** [comment]
@ybendito link to WS2019 results: https://www.dropbox.com/scl/fo/ic9qp9fsyj5xbuof4ekfu/ANA6m8IRsqbKTMdjtiVS0XY?rlkey=ec3otizyknrw67fgwwhwlr4hn&st=03beaoj3&dl=0

**Comment by ybendito** [comment]
@kostyanf14 Can you please for comparison make a test on NetKVM-Win11_24H2x64_host_uefi_viommu with vhost=off?

**Comment by kostyanf14** [comment]
@ybendito Results of NetKVM-Win11_24H2x64_host_uefi_viommu with vhost=off look similar https://www.dropbox.com/scl/fo/fp46jbzx6ycndx8abmkx3/AFLuS8ERIrP4Az1_Jtz68Tw?dl=0&e=1&lst=&rlkey=b55afynmwix0nlo5kktvu4rhk

**Comment by kostyanf14** [comment]
@YanVugenfirer @ybendito 
We have an issue in HCK-CI and iommu device flags were missing. Reruned Win11 24H2 with proper QEMU CLI.
Results: https://people.redhat.com/~kkostiuk/auto_hck/virtio-win/kvm-guest-drivers-windows/NetKVM-Win11_24H2x64_host_uefi_viommu/2024_11_06_07_44_33/results.html

**Comment by kostyanf14** [comment]
@YanVugenfirer @ybendito NetKVM-Win11_24H2x64_host_uefi_viommu passed all expected tests

**Comment by YanVugenfirer** [comment]
@kostyanf14 are we waiting for more results?

**Comment by kostyanf14** [comment]
@YanVugenfirer What with server 2025?

**Comment by ybendito** [comment]
Let's run the server 2025 again. If continues to fail I'll start investigating it, but I do not think it is related to DMAR (it runs without IOMMU). It is a question whether we want to update server 2025 to the latest one (Nov 1)

**Review by YanVugenfirer — APPROVED** [review]

**Pull request merged**
