### PR TITLE
vioscsi: disable DMAR in the iNF file

### PR DESCRIPTION
**Pull request by ybendito**
https://issues.redhat.com/browse/RHEL-62318
https://issues.redhat.com/browse/RHEL-58680
Disable DMAR for storage drivers for now.

### CODE REVIEW

**Review by vrozenfe — APPROVED** [review]

**Comment by benyamin-codez** [comment]
@ybendito, @kostyanf14, @vrozenfe & @YanVugenfirer:

Could it be the `NTDDI_VERSION`...?

Vadim speaks to DMA Remapping Support here: https://issues.redhat.com/browse/RHEL-62318?focusedId=25804762&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25804762

However, at least the Win10 build is only `ABRACADABRA_THRESHOLD | Windows 10.0.10240 | 1507 | Threshold 1`...
Is the Win11 build the same?

In vioscsi, I developed logging for `NTDDI_VERSION` per:

https://github.com/benyamin-codez/kvm-guest-drivers-windows/blob/bc85387690c04baaf21adad52b2ee827c3f740f3/vioscsi/vioscsi.c#L647-L702

...and extra defs:

https://github.com/benyamin-codez/kvm-guest-drivers-windows/blob/bc85387690c04baaf21adad52b2ee827c3f740f3/vioscsi/vioscsi.c#L647-L702

... but there is no `PreprocessorDefinitions` in `vioscsi.vcxproj` (or other method) to raise `NTDDI_VERSION` to `ABRACADABRA_WIN10_RS4 | Windows 10.0.17134 | 1803 | Redstone 4`.

Perhaps it is preferable to raise it to `ABRACADABRA_WIN10_RS5 | Windows 10.0.17763 | 1809 | Redstone 5`.

It is perhaps noteworthy that `ConfigInfo->DmaAddressWidth` requires `NTDDI_VERSION >= NTDDI_WIN10_VB` (`ABRACADABRA_WIN10_VB | Windows 10.0.19041 | 2004 | Vibranium`), but this is above Windows Server 2019.

Also, Win11 starts at `NTDDI_VERSION >= NTDDI_WIN10_CO`...
...(`ABRACADABRA_WIN10_CO | Windows 10.0.19044-22000 | 21H2 | Cobalt`)...

PR #1179 is a duplicate, yes...?

Best regards,
Ben

**Comment by benyamin-codez** [comment]
My bad for the edits... 8^d

**Comment by kostyanf14** [comment]
> PR https://github.com/virtio-win/kvm-guest-drivers-windows/pull/1179 is a duplicate, yes...?

other driver, viostor not vioscsi

**Comment by YanVugenfirer** [comment]
@benyamin-codez @ybendito @vrozenfe @kostyanf14 

@benyamin-codez Thanks a lot for the investigation!

As we now have two separate packages for Windows 10 and Windows 11, the proposed solution is to split based on our current packaging. 

The patches will be sent later by @ybendito

**Pull request merged**
