### PR TITLE
[viostor] Backport vioscsi SendSRB fixes and improvements

### PR DESCRIPTION
**Pull request by benyamin-codez**
Backports fixes and improvements from vioscsi PRs #1150 and #1162

virtqueue struct vq was also removed in favour of adaptExt->vq[QueueNumber], which results in a minor performance increase.

### CODE REVIEW

**Comment by benyamin-codez** [comment]
This will likely fix issues #756 and #907.

**Comment by benyamin-codez** [comment]
@kostyanf14

I'm taking a punt that you're the person to ask the following. Please let me know if I should ask someone else.
Any idea why the checks are failing here and for #1175 also?
Looks like mostly file not found errors or what look to be environment-based unexpected reboots...
Is there a temporary problem with the test environment...?
Would appreciate your insight, especially if there are problems with my PRs...!
Best regards,
Ben

**Comment by kostyanf14** [comment]
@benyamin-codez 

We have an upstream bug for vioscsi. Viostor is unexpected behavior, we need to investigate the reason.

**Comment by benyamin-codez** [comment]
@kostyanf14 

From a quick look it appears to be the same issue, i.e. an unexpected 0x80070002 on a file copy...

**Review by vrozenfe — APPROVED** [review]

**Comment by benyamin-codez** [comment]
@YanVugenfirer 

If I'm not mistaken, this one should be good to go too, per https://github.com/virtio-win/kvm-guest-drivers-windows/pull/1181#issuecomment-2466981842.
I note I have presumed (imho, fairly) that the `resend` logic wrapping the spinlocks in `RhelDoFlush()` is still valid.

Best regards,
Ben

cc: @vrozenfe, @kostyanf14

**Comment by YanVugenfirer** [comment]
Thanks!

**Comment by robleady** [comment]
Can anyone advise if these fixes to viostor have made it into the binary downloads available from [https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/) yet?
I can't see any mention in the changelogs there as to what's included.

**Comment by benyamin-codez** [comment]
@robleady 

I don't believe they are in v266. See my comment [here](https://github.com/virtio-win/kvm-guest-drivers-windows/pull/1196#issuecomment-2490465751).
Per Vadim's comment above that post, the _next stable public build will be released in mid-end of January 2025_.

**Comment by benyamin-codez** [comment]
**_Note:_** PR #1281 raised to fix regression introduced by this PR.

**Pull request merged**
