### PR TITLE
Vioscsi: code cleanup

### PR DESCRIPTION
**Pull request by irudakov77**
Remove unused code (was "Up to 15% disk performance gain.")

### CODE REVIEW

**Comment by vrozenfe** [comment]
@irudakov77 

Hi Ilya ,
Thank you for your patch series. I have a couple of comments on it.

"remove workitem code" - while I'm absolutely fine with removing the workitems from the code, I think that I have to explain 
why we still have it there. I added this code at the early stages of working on multi-queue  support and found it working quite
well, especially when it comes to cpu usage, but later on decided to get rid of it due to its complicity. This code was completely removed from our production branch long time ago. For the upstream it was a different story, because I was suggested to keep it as is since the code was published upstream and might be used by other vendors. The idea of using workitems as a some substitution of threaded dpc (in case when threaded dpc is not available on pre RS5 ssytems) might be quite useful if we will try to implement polling or hybrid polling mechanism instead or in addition to the classic interrupt handlers.
My conclusion on this patch - just send it separately to make it simple to apply or postpone it.

"remove pending srb list " - did you check this patch on multiple LUNs setup, when you hit StorPortBusy ? In this case storport will pause the requests queue for 250msec. If we want to make it properly, then in addition to this patch we might need to trim 
MaxNumberOfIO down to MaxIOsPerLun somewhere around
https://github.com/virtio-win/kvm-guest-drivers-windows/blob/master/vioscsi/vioscsi.c#L610

"using locks from viostor" - do you see any performance improvement with this patch? In which scenario/load? Can you please share the numbers?

Best regards,
Vadim.

**Comment by irudakov77** [comment]
@vrozenfe
 
Hi Vadim.

Thanks for the detailed comments, they are very helpful. Now it's my turn to explain. :) We are faced with a big performance difference between vioscsi and viostor (up to 4x for fast storage). Increasing the block to 512 pages has greatly reduced the difference, but it is still large. On my sata ssd disk, according to the fio test logs, viostor is 1.5 times faster in Win2019 and 1.8 times faster in Win2012. I used WPA and found that CPU consumption was 50-60% during the vioscsi test, instead of 5-6% in the viostor test. DPCs take 3 times longer to run and I didn't find out a specific reason yet.
I was going to enable work items but could not build the driver. This code doesn't work and it is better to remove it. Then I tried to reduce the runtime of VioScsiStartIo and just used a similar code from viostor. And it really got a little better, but not enough.  According to WPA, VioStorVQLock is slightly faster, so I just copied it to vioscsi. I tested performance not for every patch, but for a series. I have not checked multiple LUNs setups.
What if we drop this PR, I make a new one for work items only and create a vioscsi performance issue with WPA logs and graphs attached and we continue to discuss it in more detail?

Regards,
Ilya

**Comment by vrozenfe** [comment]
@irudakov77 

Hi Ilya
Yep, viostor is my pet :)  It supposed to be a bit faster than vioscsi, however 1.5/1.8 times difference looks very suspensios. I've never got such huge difference between these two drivers. Just for my education purpose, can you please post qemu command line for virtio-blk and virtio-scsi and give me some details on your storage backend? I usually run my tests on a dedicated NVMe SSD LUN and "scsi_debug  delay=0 ..." trying to minimize the HW related latency.

Apart from that, spiting the current series into code cleanup and performance improvement patches will be a good idea.

Best,
Vadim.

**Comment by irudakov77** [comment]
@vrozenfe

Hi Vadim.

This is the first time we discovered an issue with guest images on distributed storage (high throughput, high latency). On the customer's config with the NVMe SSD array, for scsi we got 440 MB/s (with PhysicalBreaks == 0xff, this was the old driver), and 2150 MB/s for virtio-blk. Win2012r2 guest, test command "fio --ioengine=windowsaio --iodepth=512 --rw=write --bs=1m --direct=1 --size=16G --numjobs=16 --runtime=250". At the same time, in our lab, we got about 380 MB/s in fio test for both HBAs with the same host settings, but with a different storage backend. At_io_iops test showed virtio-blk was 2 times faster (210 and 440).
On my equipment, I use a SSD SATA, the cpus and numjobs are reduced to 6, other guest settings are the same. On average, for Win2012r2, scsi shows 117 MB/s, virtio-blk -156 MB/s. For Win2019,  127 MB/s and 137 MB/s, respectively, which is not so bad :) but during scsi test, the CPU consumption is always more than 50%. Blk always uses less then 10%. I didn't know anything about scsi_debug.
I am using libvirt to manage guests, this is a snippet of its qemu command line: qemu-kvm -name guest=scsi2019,debug-threads=on -machine pc-i440fx-vz7.12.0,accel=kvm,usb=off,dump-guest-core=off -cpu Haswell-noTSX-IBRS,vme=on,ss=on,vmx=off,f16c=on,rdrand=on,hypervisor=on,arat=off,tsc_adjust=on,md-clear=on,stibp=on,ssbd=on,xsaveopt=on,pdpe1gb=on,abm=on,ibpb=on -m 4096 -smp 6,sockets=1,cores=6,threads=1 virtio-scsi-pci,id=scsi0,bus=pci.0,addr=0x4 -drive file=/vz/vmprivate/3cbab32d-c9a8-47a7-8cb6-0c692023fda8/harddisk.hdd,format=qcow2,if=none,id=drive-virtio-disk0,cache=none,discard=unmap,aio=native -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x8,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=1,write-cache=on,serial=d55590cbd0bc489a9cb3 -drive file=/vz/vmprivate/3cbab32d-c9a8-47a7-8cb6-0c692023fda8/harddisk2.hdd,format=qcow2,if=none,id=drive-scsi0-0-0-0,cache=none,discard=unmap,aio=native -device scsi-hd,bus=scsi0.0,channel=0,scsi-id=0,lun=0,device_id=14488f41fcdb4385a84b,drive=drive-scsi0-0-0-0,id=scsi0-0-0-0,bootindex=4,product=Vz HARDDISK0,write-cache=on,serial=14488f41fcdb4385a84b

Regards,
Ilya

**Comment by vrozenfe** [comment]
@irudakov77 

Hi Ilya,
can it be that one of the devices is running in multi-queue mode while another one isn't?

Regards,
Vadim.

**Comment by irudakov77** [comment]
@vrozenfe 

Hello Vadim,

Hmm, good idea. Does multiqueue imply using of iothreads? We don't use iothreads either for vioscsi or for viostor by default. I can't check the fast cluster, however on my rig I see no difference in the command line for both types of adapter: 
-device virtio-scsi-pci,id=scsi0,bus=pci.0,addr=0x5 
-drive file=/vz/vmprivate/32d661aa-2209-4e36-957a-e4cb703858da/harddisk.hdd,format=qcow2,if=none,id=drive-scsi0-0-0-0,cache=none,discard=unmap,aio=native 
-device scsi-hd,bus=scsi0.0,channel=0,scsi-id=0,lun=0,device_id=94cbe4b9c17042efadac,drive=drive-scsi0-0-0-0,id=scsi0-0-0-0,bootindex=1,product=Vz HARDDISK0,write-cache=on,serial=94cbe4b9c17042efadac
-drive file=/vz/vmprivate/318ea061-b1b9-4577-a26a-5dc745d38cea/whqldisk2.hdd,format=qcow2,if=none,id=drive-scsi0-0-1-0,cache=none,discard=unmap,aio=native 
-device scsi-hd,bus=scsi0.0,channel=0,scsi-id=1,lun=0,device_id=56438b6d03fb4c2f9b8f,drive=drive-scsi0-0-1-0,id=scsi0-0-1-0,product=Vz HARDDISK1,write-cache=on,serial=56438b6d03fb4c2f9b8f 
-drive file=/vz/vmprivate/32d661aa-2209-4e36-957a-e4cb703858da/whqldisk.hdd,format=qcow2,if=none,id=drive-virtio-disk0,cache=none,discard=unmap,aio=native -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x9,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=5,write-cache=on,serial=ac25853fc535437a8171

Regards,
Ilya

**Comment by vrozenfe** [comment]
Hi Ilya,
I included your patch into PR 684
https://github.com/virtio-win/kvm-guest-drivers-windows/pull/684/commits/28f16b035adb73b839ac9ca2203f0a3661708166
Thanks a lot,
Vadim.

**Comment by YanVugenfirer** [comment]
Included in PR#684

**Comment by irudakov77** [comment]
Hi, Vadim. Thanks.

**Pull request closed without merging**
