### PR TITLE
[IVSHMEM] Support win7

### PR DESCRIPTION
**Pull request by assorted**

### CODE REVIEW

**Comment by YanVugenfirer** [comment]
Thanks!

In general, patches look OK. I am waiting for the CI to finish to run.
But, we require to have "Signed-off-by" in the commit message (example: https://github.com/virtio-win/kvm-guest-drivers-windows/commit/c0727a156f0b80d9a487f15955a29b4af194c5fb)

Can you fix the commit message?

**Comment by YanVugenfirer** [comment]
Hi,

Can you clean up the commits first?

We don't need the merge commit "6b25c04".

You can use "git rebase -i" to re-fix the commits and then force push to your branch. It will update automatically the PR.

**Comment by assorted** [comment]
Done.

**Comment by YanVugenfirer** [comment]
Thanks!

**Pull request merged**
