### PR TITLE
[vioscsi] bugfix for BZ#1998473 windows guest can not boot with indirect_desc=off

### PR DESCRIPTION
**Pull request by vrozenfe**
regression introduced by commit c62a8a2c7bf73541fcfd6bc43bcf85147abf2620

Signed-off-by: Vadim Rozenfeld <vrozenfe@redhat.com>

### CODE REVIEW

**Comment by tomty89** [comment]
This is such an odd fix. Let alone the fact that NOPB is "retreated" to 32(+1) instead of 64(+1), I am not seeing the sense/logic of this fix (well, and the original bug report). The bug report claims that `indirect_desc=off` was problematic (and at least hinted/implied that things were fine with `indirect_desc=on`), but before the fix NOPB was identical in both cases. What even weirder is, in the "procedures to reproduce", `indirect_desc=off` was not used at all, and then some other people just pops out and say "with the command in that I confirm that the problem is fixed". The whole process is like a mess. It seems like no one really cares about all the details and what was actually wrong / should be the right fix.

Let alone whether NOPB can really be bumped over 64(+1) for most drives, shouldn't we investigate / can anyone tell whether it has something to do with this block? (Which is the only other one varies with `adaptExt->indirect`.)

https://github.com/virtio-win/kvm-guest-drivers-windows/blob/a54882c4fc4bfec8d5abb583ca84a3778c6e8bd4/vioscsi/vioscsi.c#L602-L606

**Comment by YanVugenfirer** [comment]
@tomty89 
Frankly disabling indirect descriptors looks like a complete corner case. It is hard to imagine why anyone would disable indirect buffers after so many years the feature exists. So, I personally don't expect anyone from the community to pop up and comment on the fix.
On other hand, there is a reference to Red Hat BZ#1998473 (https://bugzilla.redhat.com/show_bug.cgi?id=1998473). Red Hat QE will check (actually already checked) the fix.

I don't understand what are you compianing about. In general case (with inderect buffers), the
```
    if(adaptExt->dump_mode) {
          ConfigInfo->NumberOfPhysicalBreaks  = SCSI_MINIMUM_PHYSICAL_BREAKS;
      } else {
          adaptExt->max_physical_breaks = MAX_PHYS_SEGMENTS;
          adaptExt->max_physical_breaks = PHYS_SEGMENTS;
  #if (NTDDI_VERSION > NTDDI_WIN7)
          if (adaptExt->indirect) {
              adaptExt->max_physical_breaks = MAX_PHYS_SEGMENTS;
              VioScsiReadRegistry(DeviceExtension);
          }
  #endif

**Comment by YanVugenfirer** [comment]
Regarding the process. 

Maybe we can do a better job describing it, but it is far from the "mess":
1. Each PR is peer reviewed by the team working on virtio-win drivers
2. Each PR goes over WHQL tests with our HCK-CI. Same tests that are used for certifications (yes, there could be holes in CI, like in the case of the original PR that caused the problem, because it runs on a specific configurations)
3.  Red Hat QE is testing each commit referenced with Red Hat BZ and also tests versions that are released.
4. We didn't promiss in any place (and such promiss is impossible) that master is always stable. It might break from time to time, although we make extra effort comparing to other projects that this will not happen.

**Comment by mbilker** [comment]
I was able to reproduce the issue by using LUN passthrough (`device="lun"`) through libvirt under RHEL 8.4. If I switch to block-device backed storage (`device="block"`), then the VM boots up fine. Therefore, the bug is not limited to only `indirect_desc=off` unless using LUN passthrough defaults to using `indirect_desc=off`. Reverting back to 100.85.104.19900 from 2021-05-16 allowed me to boot Windows with LUN passthrough.

**Comment by vrozenfe** [comment]
@mbilker 
Does it happen with the latest/stable drivers available at https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.208-1/virtio-win.iso ? Can you please post the entire qemu command line and the qemu version?

Thanks,
Vadim.

**Comment by mbilker** [comment]
> Does it happen with the latest/stable drivers available at https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.208-1/virtio-win.iso ?
Yes it still occurs with this version.

> Can you please post the entire qemu command line and the qemu version?
```
/usr/libexec/qemu-kvm -name guest=vgpu1,debug-threads=on -S -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-8-vgpu1/master-key.aes -blockdev {"driver":"file","filename":"/usr/share/edk2/ovmf/OVMF_CODE.secboot.fd","node-name":"libvirt-pflash0-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-pflash0-format","read-only":true,"driver":"raw","file":"libvirt-pflash0-storage"} -blockdev {"driver":"file","filename":"/var/lib/libvirt/qemu/nvram/vgpu1_VARS.fd","node-name":"libvirt-pflash1-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-pflash1-format","read-only":false,"driver":"raw","file":"libvirt-pflash1-storage"} -machine pc-q35-rhel8.2.0,accel=kvm,usb=off,vmport=off,smm=on,dump-guest-core=off,kernel_irqchip=on,pflash0=libvirt-pflash0-format,pflash1=libvirt-pflash1-format -cpu host,hypervisor=off,vmx=off,hv-time,hv-relaxed,hv-vapic,hv-spinlocks=0x1fff,hv-vpindex,hv-runtime,hv-synic,hv-stimer,hv-vendor-id=1234567890ab,hv-frequencies,hv-ipi,kvm=off,host-cache-info=on,l3-cache=off -global driver=cfi.pflash01,property=secure,value=on -m 4096 -overcommit mem-lock=off -smp 3,sockets=1,dies=1,cores=3,threads=1 -uuid a6911b76-56e4-4871-b90b-c366941032f2 -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=37,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc,clock=vm,driftfix=slew -global kvm-pit.lost_tick_policy=delay -no-hpet -no-shutdown -global ICH9-LPC.disable_s3=1 -global ICH9-LPC.disable_s4=1 -boot strict=on -device pcie-root-port,port=0x10,chassis=1,id=pci.1,bus=pcie.0,multifunction=on,addr=0x2 -device pcie-root-port,port=0x11,chassis=2,id=pci.2,bus=pcie.0,addr=0x2.0x1 -device pcie-root-port,port=0x12,chassis=3,id=pci.3,bus=pcie.0,addr=0x2.0x2 -device pcie-root-port,port=0x13,chassis=4,id=pci.4,bus=pcie.0,addr=0x2.0x3 -device pcie-root-port,port=0x14,chassis=5,id=pci.5,bus=pcie.0,addr=0x2.0x4 -device pcie-root-port,port=0xd,chassis=6,id=pci.6,bus=pcie.0,addr=0x2.0x5 -device qemu-xhci,p2=15,p3=15,id=usb,bus=pci.2,addr=0x0 -device virtio-scsi-pci,id=scsi0,bus=pci.4,addr=0x0 -device virtio-serial-pci,id=virtio-serial0,bus=pci.3,addr=0x0 -blockdev {"driver":"host_device","filename":"/dev/disk/by-id/scsi-0ATA_SATA_SSD_20051212801875","aio":"native","node-name":"libvirt-2-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-2-format","read-only":false,"discard":"unmap","detect-zeroes":"unmap","cache":{"direct":true,"no-flush":false},"driver":"raw","file":"libvirt-2-storage"} -device scsi-block,bus=scsi0.0,channel=0,scsi-id=0,lun=0,drive=libvirt-2-format,id=scsi0-0-0-0,bootindex=1 -blockdev {"driver":"file","filename":"/iso/virtio-win.iso","node-name":"libvirt-1-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-1-format","read-only":true,"driver":"raw","file":"libvirt-1-storage"} -device ide-cd,bus=ide.2,drive=libvirt-1-format,id=sata0-0-2 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -chardev spicevmc,id=charchannel0,name=vdagent -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=com.redhat.spice.0 -chardev socket,id=charchannel1,fd=39,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=2,chardev=charchannel1,id=channel1,name=org.qemu.guest_agent.0 -tpmdev emulator,id=tpm-tpm0,chardev=chrtpm -chardev socket,id=chrtpm,path=/run/libvirt/qemu/swtpm/8-vgpu1-swtpm.sock -device tpm-crb,tpmdev=tpm-tpm0,id=tpm0 -device usb-tablet,id=input0,bus=usb.0,port=1 -spice port=5900,addr=127.0.0.1,disable-ticketing,seamless-migration=on -device qxl-vga,id=video0,ram_size=67108864,vram_size=67108864,vram64_size_mb=0,vgamem_mb=16,max_outputs=1,bus=pcie.0,addr=0x1 -device vfio-pci,host=0000:02:00.0,id=hostdev0,bus=pci.5,addr=0x0 -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on
```
```
$ /usr/libexec/qemu-kvm -version
QEMU emulator version 4.2.0 (qemu-kvm-4.2.0-48.module+el8.4.0+11909+3300d70f.3)
Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers
```

**Comment by vrozenfe** [comment]
@mbilker 

Thanks Matt,
I will ask QE to look into this issue.
Vadim.

**Comment by peixiu** [comment]
Hi all, 

Thanks for your information, This issue is similar with this one https://github.com/virtio-win/kvm-guest-drivers-windows/issues/657, I tried with a LIO-ORG lun disk /dev/disk/by-id/scsi-SLIO-ORG_disk0_18d13542-7ace-49df-b919-46240cfa05e7 to replace the case used host device /dev/disk/by-id/scsi-0ATA_SATA_SSD_20051212801875, But I didn't reproduce this issue. It seems LIO-ORG lun cannot match this case's requirement, I'll try to find a host with a real hard disk and try it again, I'll update the result here asap.

Best Regards~
Peixiu

**Comment by vrozenfe** [comment]
@peixiu, @mbilker 

Can you please check the value of "max_segments" for the relevant devices?
It should be something as follow:
[vrozenfe@virtowin ~]$ cat /sys/block/nvme0n1/queue/max_segments 

Thanks,
Vadim.

**Comment by peixiu** [comment]
[root@dell-per730-48 home]# lsscsi
[0:2:0:0]    disk    DELL     PERC H730 Mini   4.27  /dev/sda 
[1:0:0:0]    disk    Kingston DT 101 G2        PMAP  /dev/sdb 
[12:0:0:0]   disk    LIO-ORG  disk0            4.0   /dev/sdc 
[root@dell-per730-48 home]# cat /sys/block/sdc/queue/max_segments 
2048

**Comment by mbilker** [comment]
> Can you please check the value of "max_segments" for the relevant devices? It should be something as follow: [vrozenfe@virtowin ~]$ cat /sys/block/nvme0n1/queue/max_segments

```
$ lsscsi
[0:0:0:0]    disk    ATA      PNY CS900 240GB  0P13  /dev/sda
[1:0:0:0]    disk    ATA      SATA SSD         61.3  /dev/sdb
$ cat /sys/block/sdb/queue/max_segments
168
```

**Comment by peixiu** [comment]
Reproduced this issue with a SATA SSD disk, we can track this issue and https://github.com/virtio-win/kvm-guest-drivers-windows/issues/657 with the same bz: https://bugzilla.redhat.com/show_bug.cgi?id=2022656

SATA disk info:
 # lsscsi
[0:0:11:0]   disk    ATA      INTEL SSDSC2CT06 300i  /dev/sda 
[0:2:0:0]    disk    IBM      ServeRAID M5210  4.22  /dev/sdb 
# cat /sys/block/sda/queue/max_sectors_kb 
256
cat /sys/block/sda/queue/max_segments
64
# cat /sys/block/sda/queue/max_hw_sectors_kb 
256
cat /sys/block/sda/queue/hw_sector_size 
512

Thanks~
Peixiu

**Pull request merged**
