### PR TITLE
Moving functionality of netkvmco.dll to netkvco.exe

### PR DESCRIPTION
**Pull request by ybendito**
The PR is not for merge at this moment, need to wait for proper time, as netkvmco.dll functionality is used in 'avocado-vt'.
netkvmco.dll is removed from the release and converted to executable,
netkvmco.exe is added it terminates all the calls that previously were terminated by netshell.
Example of use: netkvmco show parameters 0

### CODE REVIEW

**Comment by kostyanf14** [comment]
NetKVM-Win2019x64-2023_07_07_20_21_48 results - https://www.dropbox.com/sh/qxq4smeqzjzcmgw/AABfvoHwljE0PI8EjhXdi6f8a?dl=0&lst=

**Comment by ybendito** [comment]
> NetKVM-Win2019x64-2023_07_07_20_21_48 results - https://www.dropbox.com/sh/qxq4smeqzjzcmgw/AABfvoHwljE0PI8EjhXdi6f8a?dl=0&lst=

@kostyanf14 Due to some reason there is no HLKX file

**Comment by kostyanf14** [comment]
> > NetKVM-Win2019x64-2023_07_07_20_21_48 results - https://www.dropbox.com/sh/qxq4smeqzjzcmgw/AABfvoHwljE0PI8EjhXdi6f8a?dl=0&lst=
> 
> @kostyanf14 Due to some reason there is no HLKX file

@ybendito  Last test is still in progress, HLKX uploads only after all tests

**Comment by kostyanf14** [comment]
NetKVM-Win2022x64 create project_package

**Comment by ybendito** [comment]
NetKVM-Win2019x64 - completely unclear. One test "Offload checksum" is marked as failed. The log of ndis test does not contain any failure.

**Review by YanVugenfirer — APPROVED** [review]

**Pull request merged**
