### PR TITLE
vioscsi: Add more robust routine to read registry parameters

### PR DESCRIPTION
**Pull request by sb-ntnx**
This PR is to change implementation of VioScsiReadRegistryPhysicalBreaks to make it read a passed parameter instead of hardcoded one. If we need to add more parameters via registry, it will help us avoid bloat of the code with multiple functions to read various registry values. 

HLK2022 and HCK (Windows 2012R2) passed all tests as expected (without new failures). Build was done using EWDK2022.

### CODE REVIEW

**Review by vrozenfe — APPROVED** [review]

**Comment by JonKohler** [comment]
Nice, good job

**Review by YanVugenfirer — APPROVED** [review]

**Comment by YanVugenfirer** [comment]
Thanks! Waiting for CI to run before merging.

**Comment by sb-ntnx** [comment]
Hey @YanVugenfirer, can you let me know which test failed as the dropbox folder is empty? I have executed HLK for Windows 2019 in my environment and all tests (except blacklisted) passed successfully.

**Comment by kostyanf14** [comment]
Hi @sb-ntnx, Failed: DF - Reinstall with IO Before and After (Reliability)

**Comment by sb-ntnx** [comment]
I've rerun the check 4 times on Windows 2019 and it never failed. Seems like this time CI jobs also completed without any failures.

**Comment by YanVugenfirer** [comment]
OK. Merging.

**Pull request merged**
