### PR TITLE
[viostor] the host process the VIRTIO_BLK_T_GET_ID, return the sn aft…

### PR DESCRIPTION
**Pull request by jackli577**
…er the guest query. the sn is default zero.

### CODE REVIEW

**Comment by jackli577** [comment]
i see again, no error, and  git the master compare again,

**Comment by YanVugenfirer** [comment]
I am checking out the pull request branch by (as described here: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally):

git fetch origin pull/426/head:PR426
git checkout PR426

**Comment by jackli577** [comment]
C:\work\public\kvm-guest-drivers-windows>git fetch origin pull/426/head:PR426
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 6 (delta 4), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (6/6), done.
From https://github.com/virtio-win/kvm-guest-drivers-windows
 * [new ref]           refs/pull/426/head -> PR426

C:\work\public\kvm-guest-drivers-windows>git checkout PR426
Switched to branch 'PR426'

i build also, had no error. 
build x64 win10
vs2015
wdk is 7600.16385.1

any diff?

**Comment by ybendito** [comment]
All the projects are built with 2017 and with wdk 1809.
Is it not enough to build x64 win10. Use buildall.bat at the root.
See https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/Building-the-drivers

**Comment by jackli577** [comment]
> All the projects are built with 2017 and with wdk 1809.
> 7600.16385.1 is still used to build drivers for legacy platforms (vista and below),
> Is it not enough to build x64 win10. Use buildall.bat at the root.
> See https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/Building-the-drivers
> For faster build to check for compilation errors you can run buildall_nosdv

ok， thanks， i will do it later。

**Comment by jackli577** [comment]
> All the projects are built with 2017 and with wdk 1809.
> 7600.16385.1 is still used to build drivers for legacy platforms (vista and below),
> Is it not enough to build x64 win10. Use buildall.bat at the root.
> See https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/Building-the-drivers
> For faster build to check for compilation errors you can run buildall_nosdv

i am sorry to do this later(wokrday too busy)， i check the code， update it， please check again。

**Pull request merged**
