### PR TITLE
[vioscsi] fix for BZ#2118630 saving BSOD crash dumps fails

### PR DESCRIPTION
**Pull request by vrozenfe**
Reported-by : main@ehvag.de
https://github.com/virtio-win/kvm-guest-drivers-windows/issues/809

Signed-off-by: Vadim Rozenfeld <vrozenfe@redhat.com>

### CODE REVIEW

**Comment by JonKohler** [comment]
Broken by my commit on #736 - sorry for the breakage, I didn't test BSOD saves in our setup during development, my mistake entirely!

@YanVugenfirer - is this something that the HCK has coverage for? Curious how it slipped through, or if this is a test case that needs to get added?

FYI @sb-ntnx - this would be a problem for us when we pick up the commit I did around max IO sizes, regardless of IO size/breaks configuration

**Comment by sb-ntnx** [comment]
@JonKohler, I am aware of the issue as I am monitoring this repo. I checked it in my morning and it could be reproduced with the build that I had ready in January, so I doubt it is your commit. 
HCK/HLK is a Microsoft test suite and it does not check whether a dump can or cannot be generated. Also, if I am not mistaken, some of HCK/HLK tests require a device removal, so in my setup system drive is also using SATA bus, so even if we hit a BSOD during any HCK/HLK test (it is not uncommon), the dump will be collected properly.

**Comment by vrozenfe** [comment]
@JonKohler @sb-ntnx 
This bug is fully mine, introduced with the following commit a54882c4fc4bfec8d5abb583ca84a3778c6e8bd4
Even though that the problem is reproducible only in crash dump stack and only on 64-bit platforms, it is
very sad  that the problem was not discovered and fixed earlier. We will bring the QE attention to check not
only presence MEMORY.DMP file but also the crash dump consistency bu running dumpchk utility or by
opening a generated crash dump file with WinDbg.

Vadim.

**Comment by sb-ntnx** [comment]
I have also verified the fix on W2022 and it works fine, no issues found in HLK2022 either. Thanks Vadim.

**Comment by vrozenfe** [comment]
@sb-ntnx 
Thank you for your feedback, Sergey.
Cheers,
Vadim.

**Review by YanVugenfirer — APPROVED** [review]

**Comment by YanVugenfirer** [comment]
> @JonKohler @sb-ntnx This bug is fully mine, introduced with the following commit [a54882c](https://github.com/virtio-win/kvm-guest-drivers-windows/commit/a54882c4fc4bfec8d5abb583ca84a3778c6e8bd4) Even though that the problem is reproducible only in crash dump stack and only on 64-bit platforms, it is very sad that the problem was not discovered and fixed earlier. We will bring the QE attention to check not only presence MEMORY.DMP file but also the crash dump consistency bu running dumpchk utility or by opening a generated crash dump file with WinDbg.
> 
> Vadim.

We are also exploring to add additional tests to CI other than HCK. The first candidate will be virtio-fs driver, where HCK is not texting file system functionality (because the driver itself is just simple WDF driver). So it could be that in the future we will add more tests. The problem of course is the amount of time it takes to execute CI pipeline.

Best regards,
Yan.

**Pull request merged**
