### PR TITLE
Gpu

### PR DESCRIPTION
**Pull request by vrozenfe**
Kernel mode part for Bug 1923886 - Windows virtio-gpu dod driver cannot change resolution automatically

### CODE REVIEW

**Review by YanVugenfirer — APPROVED** [review]
@vrozenfe Vadim, if not urgent, please don't merge yet. I want to ensure that HCK-CI runs on virtio-gpu driver as well.

Thanks.

**Comment by vrozenfe** [comment]
Sure, it can wait.
I'm going to submit UM part in a day or two.
Best,
Vadim.

**Comment by KrutavShah** [comment]
When will these changes be merged?

Thanks, from Krutav Shah.

**Comment by YanVugenfirer** [comment]
> When will these changes be merged?
> 
> Thanks, from Krutav Shah.
A fix needed for the failure during CI (crash) and waiting for the user part of the change that PR addresses.

Best regards,
Yan.

**Comment by vrozenfe** [comment]
Since the UM code needs to be applied on top of KM part, I am going yo merge this series now. 
I did try to reproduce DF failure reported by Yan on my testing setup Unfortunately without success. 
Hopefully our QE will manged to reproduce it. In any case the entire WHQL re-testing will be required
soon. 

Best regards,
Vadim.

**Pull request merged**
