### PR TITLE
add CI/CD

### PR DESCRIPTION
**Pull request by lersi**

### CODE REVIEW

**Comment by kostyanf14** [comment]
Hi @lersi,

Any reason to run the build with GitHub Action in parallel with the existing CI?

**Comment by lersi** [comment]
Hello @kostyanf14,
This pull request was made by mistake, but I am working on adding GitHub CI.

I did not know that there is an existing CI. where can I find the configuration file?
In addition, if you have a build CI, why you don't include the build artifacts in the releases?

**Comment by kostyanf14** [comment]
Hi @lersi 

You can find CI checks in all PRs (for example https://github.com/virtio-win/kvm-guest-drivers-windows/pull/939 -> `HCK-CI [EWDK] — Build finished.`)

>  where can I find the configuration file?

Unfortunately, there is no public config file.

> In addition, if you have a build CI, why you don't include the build artifacts in the releases?

This is redundant. The test-signed driver is useless for everyone except the driver developer. We build a test-signed driver and run all automatic HLK tests (all manual is skipped). CI can't sign drivers with a production signature because HLK has several manual tests. virtio-win.iso from Fedora (https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/) contains a tested and signed driver but this a long process from virtio-win repo to ISO with several manual steps. If you plan to add GitHub Action CI let's discuss this before to prevent the rejection of PR with a big work. Mail me: konstantin at daynix.com

**Comment by YanVugenfirer** [comment]
Hi @lersi,

We are open to adding integration with external CI. Do you want to have a discussion about your needs? Contact Konstantin or me at yan (at) daynix.com

**Comment by lersi** [comment]
Hello @YanVugenfirer 

Thank you very much for your openness.

I have already contacted with Konstantin, this looks like a challenging task, I am searching for a solution and I will answer him soon.

**Pull request closed without merging**
