### PR TITLE
NetKVM: Enforce driver isolation in INF files

### PR DESCRIPTION
**Pull request by kostyanf14**
Resolve: https://issues.redhat.com/browse/RHEL-26207

### CODE REVIEW

**Comment by YanVugenfirer** [comment]
Let's start with this and fix SR-IOv failover later.

**Review by YanVugenfirer — APPROVED** [review]

**Comment by ybendito** [comment]
@kostyanf14 I'd suggest to keep Win10 build to use %12 and use %13 in Win11 build.

**Comment by kostyanf14** [comment]
@ybendito 

From MSDN about DIRID13:
```
Driver package's [Driver Store](https://learn.microsoft.com/en-us/windows-hardware/drivers/install/driver-store) directory.

For Windows 8.1 and later versions of Windows, specifies the path to the Driver Store directory where the driver package was imported.
```

I ran Windows Server 2016 HLK tests "DF - InfVerif INF Verification" and "Static Tools Logo Test" and both passed.
I checked where netkvm.sys located and it is present in the Driver Store directory.

**Comment by ybendito** [comment]
@kostyanf14 If checkinf of Server 2025 WDK requires 16299 in the INF, the INF will not be installable on 2016

**Comment by kostyanf14** [comment]
@ybendito I use INF from Win10 folder (DIRI13, target 10.0)  for Server 2016. 
Only INF in Win11 folder will have DIRI13 + target 10.0.16299

**Comment by ybendito** [comment]
> @ybendito I use INF from Win10 folder (DIRI13, target 10.0) for Server 2016. Only INF in Win11 folder will have DIRI13 + target 10.0.16299

This is not in the commit, is it?

**Comment by YanVugenfirer** [comment]
> > @ybendito I use INF from Win10 folder (DIRI13, target 10.0) for Server 2016. Only INF in Win11 folder will have DIRI13 + target 10.0.16299
> 
> This is not in the commit, is it?

It is here: https://github.com/virtio-win/kvm-guest-drivers-windows/pull/1063

**Pull request merged**
